# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build: 
    working_directory: ~/stringer
    docker:
      - image: crystallang/crystal:0.29.0
    steps:
      - checkout
      - run: shards install
      - run: crystal tool format --check
      - run: bin/ameba
      - run: crystal spec
